### ISSUE TITLE
Can't sign out when signed in to multiple providers

### ISSUE THREAD

**Issue by Helveg** [abacritt/angularx-social-login#164]
When I'm signed in to both Facebook and Google I need to manually remove their cookies and other forms of local storage to sign out. Using the `authService.signOut` method throws no errors or warnings and emits an authState with user undefined but on page reload it just sends both Google and Facebook SocialUser objects again. 

Other than this bug report I'd also like to request perhaps a single-provider option that will prevent logins with multiple providers or logs out the user with their previous provider on a new sign in? 

Is there a straightforward way built into the package that I'm missing?

**Comment by Helveg** [comment]
I also experience problems signing out of Facebook in general it seems? Since there are this many open issues regarding the signing out, could you perhaps spend some attention on figuring out our issues, releasing a fix or a guide to troubleshoot these issues?

**Comment by jaibatrik** [comment]
The solution to this may require some refactoring of the AuthService and BaseLoginProvider files. It'd be great if someone can analyze and send a PR for this.

**Comment by somcoder** [comment]
I couldn't really come up with a good scenario where a user can login to an app multiple times, but this is something that needs a solution after all.
In the demo, when a user log in with a provider and then refresh the page, there's a little bit of time where it shows the providers before it knows that you are already logged in (tracked in #148), so you can login again. Let's take this as the scenario. 😀
##### A possible solution is to modify the `signOut` method of the `AuthService`, so it signs out of all providers instead of one (current implementation).

**Comment by jaibatrik** [comment]
There's a new flag introduced `autoLogin` in `SocialAuthService`. That should prevent automatic sign ins.

Other than that closing for now. Logging in with multiple provider is not a very common use case IMO.
