### ISSUE TITLE
Fb signin with scope

### ISSUE THREAD

**Issue by alexandrubobei** [abacritt/angularx-social-login#167]
When calling the login function, you always send the default scope which is { scope: 'email,public_profile' } even when the opts parameter is given. And the login asks only for email permissions even tough i send other scopes. You could assign the this.opt = opt from the parameter. This way if you five login options, you cans end these ones. If not, use the default ones.

**Comment by bbarn3y** [comment]
It partly works for me. I provided the scope for the login options parameter when creating the provider in my module declaration. Facebook asks for the declared permissions correctly (in my case user_gender and user_age_range), so my app has access for the needed permissions.

However, after a successful login, the returned object does not contain these extras and the reason seems to be that the request URL is incorrect, it does not contain the extra fields as @alexandrubobei said.
It's not really a nice solution, but since you app has access to these permissions, you can query them yourself (you need the authToken from the login result):
https://graph.facebook.com/v2.9/me?access_token=${authToken}&fields=gender%2Cage_range&method=get&pretty=0&sdk=joey&suppress_http_code=1

**Comment by jaibatrik** [comment]
PRs are welcome!

**Comment by jaibatrik** [comment]
Looks like this has been addressed. Reopen if it does not work still.
