### ISSUE TITLE
Login in facebook: Console Error

### ISSUE THREAD

**Issue by mhdbouk** [abacritt/angularx-social-login#194]
Hello, when I logout from facebook, I'm getting a console error.

1. Go to `https://abacritt.github.io/angularx-social-login/`
2. Login using facebook
3. After login is completed, click on Logout
4. Check console log, you have this message

```
You are overriding current access token, that means some other app is expecting different access token and you will probably break things. Please consider passing access_token directly to API parameters instead of overriding the global settings.
```

It is not causing any problem, but it is annoying in the console.

Thank you

**Comment by romelgomez** [comment]
In orden to prevent *You are overriding current access token* facebook sdk error/warning, you have to reuse the token of facebook that you get after login to make the request. 

This behavior is related to: 

https://developers.facebook.com/support/bugs/1047676415440644/
https://developers.facebook.com/support/bugs/2010347079075449/

Logout method should be avoid because it close the user session in Facebook too.  

Take a look to socialUser object,  if you signIn with facebook and then with google, the object  socialUser will get rewrite by google data. I think maybe this is a bug, I think they should be separated. 

```text
If avoid authService.signOut method, and: 

	[url] /sign-in-view 
		[SocialUser]: null		 

	>>> Sign-in with google with the email *alice@gmail.com*

	[url] /profiles 
		[SocialUser]: Google-Data of *alice@gmail.com* 		 

	[url] /sign-in-view 
		[SocialUser]: Google-Data of *alice@gmail.com*

  >>> sign-in with facebook  with the email  *maria@facebook.com*

	[url] /profiles 
		[SocialUser]: Facebook-Data *maria@facebook.com*

	[url] /login-view 
		[SocialUser]: Google-Data *alice@gmail.com*
```

At this moment SocialUser object of [*maria@facebook.com*] is rewrite by the previus sign-in object of [*alice@gmail.com*].

**Comment by jaibatrik** [comment]
Closing this as this does not seem to be a problem with the library itself.
