### ISSUE TITLE
Angular Build Error

### ISSUE THREAD

**Issue by sethurv** [abacritt/angularx-social-login#241]
I have tried to build the package with the help of the `Readme` document.

Following is the error observed. `The serve command requires to be run in an Angular project, but a project definition could not be found.`

I have tried with `node` version 10.12.0, 12.3.1 and 13.3.0.

1. Why `angular.json` file is not added in the repository
2. `@angular/cli` is not added in 'devDependencies'? When latest version is added this gives different set of error.
3. Where to find the 'demo' folder
4. Please mention the node and npm version in `Readme` where the package is verified. This will help to avoid any new issue introduced as part of `node.js` update.

**Comment by deyvidfk** [comment]
@sethurv 
In the project dependencies file "package.json" contains the key "**engines**" that specifies the version of the compatible nodejs.

**Comment by deyvidfk** [comment]
@sethurv
The file "package.json" contains the key "engines" that specifies the version of the compatible node.

**Comment by jaibatrik** [comment]
@sethurv Could you please elaborate on what you are trying to achieve? 

If you are trying to build the library, the command is `npm run build`. This project is a standalone library and is not an Angular app, which is why `ng serve` will not work here. The demo application got moved to https://github.com/jaibatrik/angularx-social-login-demo.

**Comment by sethurv** [comment]
@jaibatrik I was looking for the demo application. Thanks for the info.
