### ISSUE TITLE
Logout not working after once the browser is refreshed

### ISSUE THREAD

**Issue by arindammojumder** [abacritt/angularx-social-login#586]
After successful login, I can enter my application and everything is working fine.
But if I refresh the page and after that try to do socialLogout, I am getting an error. The plugin should auto-track the login status after a user refreshes the page.

**The error I am getting below:**

![image](https://user-images.githubusercontent.com/282325/185745530-d4bb8b01-0be5-46da-998e-0ed82c7c5501.png)

**Comment by professor-rage** [comment]
Regarding Google Auth, this has me unsure how to proceed with the following scenario. 

Every refresh of the browser requires the user to login again. You can listen to the authState using this.authService.authState.subscribe() but will not trigger unless the user clicks lthe login button again. 

Scenario 1: If user logs in and the browser is never refreshed, if they signout of web app, then this.authService.signOut() works appropriately.

Scenario 2: If user logs in, then closes browser, then opens the browser/web app again, through web app's auth persistence, they are still logged in, but no longer logged in to google, so when they signout of web app, this.authService.signOut() fails with the error above.  

Question, any methods/mechanisms to persist google auth when browser is refreshed?   Instead of always being logged off when the browser is closed? 

TIA
