### ISSUE TITLE
Not working on PWA

### ISSUE THREAD

**Issue by junimohano** [abacritt/angularx-social-login#6]
It is not working only on PWA mode..
It is restarts app after social login.
Is there any solutions ?????

**Comment by jaibatrik** [comment]
@junimohano Could you please elaborate what exactly you are doing?

**Comment by junimohano** [comment]
link [https://hairbookweb.azurewebsites.net/login](url)

Can you check here ?
You can use on mobile web using your phone as PWA.
It is just working on the web but not working on PWA mode.
Go to that link and try Social Login.

The problem is that, 
Once my website goes to authentication of google or facebook and come back to my website after authentication, PWA is restarted so that it is not property working.

**Comment by jaibatrik** [comment]
I tried the login with mobile, it appears to be working, isn't it? 

_Sent from my Motorola XT1572 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by junimohano** [comment]
Can you add short cut to your background of your phone?
And then, run that short cut as it is way how to run PWA.
only on PWA mode is not working.. 
I have no idea how to fix ..

**Comment by saleemepoch** [comment]
For me it's not even working from mobile browser. It flashes Google sign in then switches back to the App's login page. Doesn't log me in.

**Comment by saleemepoch** [comment]
Actually, it worked for me on PWA as well.  I should've paid more attention the console because it was trying to connect to a local api end point example.dev which was resulting in error obviously. I fixed it and yes it does give me a popup for oauth but it logs me in and brings me back to the App, and I am talking about PWA which you start from your phone.

Lesson learnt: pay closer attention to the console.

**Comment by saleemepoch** [comment]
Actually, Facebook login doesn't work with a PWA on a mobile (in my case, Android).

It loads up Facebook auth window, but it remains blank and doesn't redirect back to the app.

Apparently, it is due to Facebook API:
https://stackoverflow.com/questions/40984827/facebook-js-api-does-not-work-with-progressive-web-app

Is there a way to get adjust the code to get it working with PWA?

**Comment by sotisoti** [comment]
I am facing the same problem here, the status bar keeps showing 'Waiting for www.facebook.com' for some reason..
 
![screen shot 2018-04-07 at 9 44 47 pm](https://user-images.githubusercontent.com/9424330/38455592-f765393e-3aac-11e8-8079-6106edbdb447.png)

**Comment by loicsalou** [comment]
same problem for me. Works fine in a browser but does not work on mobile browser nor PWA installed.
I'm also looking for a correct solution in order to login to social networks from a PWA, this is a blocker for me...

**Comment by misterpy** [comment]
@loicsalou hi there. have you manage to get this working in installed PWA?

**Comment by feof** [comment]
are there news about pwa mode ?

**Comment by saleemepoch** [comment]
I somewhat managed to solve this issue, by using ngx-facebook instead.

I used FB SDK to redirect within PWA to facebook auth with a redirect parameter like so:

```
window.location.href = encodeURI('https://www.facebook.com/v3.2/dialog/oauth?client_id='
                    + environment.facebookAppId
                    + '&redirect_uri='
                    + uri + '&scope=email&response_type=token&state={login=true,location=/}');

```
So instead of triggering a popup, it would simply redirect to facebook and when you login, it redirects back to your PWA. At this stage I call this.fb.getLoginStatus() method to check if the person is logged into FB and simply log the person into PWA (and collect user details from FB, if needed).

This works on all platforms except iPhone.

https://stackoverflow.com/questions/53454186/progressive-web-app-oauth-login-not-working-on-iphone

**Comment by rwmarmol** [comment]
Hi!
Someones solved this issue? I tried with ngx-facebook and Firebase Auth and still get the same flow. It works fine in Browsers but does't in app.

**Comment by saleemepoch** [comment]
This post has the long and short of it:
https://stackoverflow.com/questions/53454186/progressive-web-app-oauth-login-not-working-on-iphone

> Windows + Chrome → SUCCESS
> Windows + Firefox → SUCCESS
> Windows + Edge → SUCCESS
> 
> Android + Chrome → SUCCESS
> Android + Standalone → SUCCESS
> 
> Mac + Chrome → SUCCESS
> Mac + Safari → SUCCESS
> 
> iPhone + Chrome → SUCCESS
> iPhone + Safari → SUCCESS
> iPhone + Standalone → !!! FAILURE !!!

**Comment by rdtandel** [comment]
It worked for iPhone 6 plus with safari browser. but not working in iPhone 7 with safari. the Login popup appears but not redirect to the page and the popup window was blank. when refresh the website login succeeded.
