### ISSUE TITLE
Version 4.1.0 still prints "deprecated" onto console

### ISSUE THREAD

**Issue by aneshodza** [abacritt/angularx-social-login#651]
Already tried to talk about it in [this issue](https://github.com/abacritt/angularx-social-login/issues/517), but it's closed so I decided to open a new one. The same issue talks about how the deprecation should be fixed in the new version, but I still get the same warning. For everyone in the future: there is a [PR which promises to fix it ](https://github.com/abacritt/angularx-social-login/pull/598), no idea when or if it will get merged tho
<img width="402" alt="image" src="https://user-images.githubusercontent.com/75726773/206651238-80f559fe-8c9b-4731-b7ab-f2ec50eb585f.png">

**Comment by anuj-scanova** [comment]
The `angularx-social-login` library has been deprecated.

Use @abacritt/angularx-social-login

**Comment by aneshodza** [comment]
More information for anyone coming after me with this issue: the PR to undeprecate it is still open. See here: https://github.com/abacritt/angularx-social-login/pull/598

**Comment by LiJell** [comment]
@aneshodza  version 4.1.0 is not updated yet I guess

**Comment by aneshodza** [comment]
Yes, sadly it isn't.

**Comment by rat-matheson** [comment]
The PR is blocked and I don't have permissions to do anything about it.  If you are stuck on this issue, you could just get the code from the PR from github (rather than waiting for it to possibly find its way into npm).

**Comment by Heatmanofurioso** [comment]
I've made a deploy with latest changes but on V12 support
https://www.npmjs.com/package/@abacritt/angularx-social-login/v/1.2.4-ngx12.0

Can you test it, please?

**Comment by rat-matheson** [comment]
I've tested this.   Works great!  Thanks for much for finishing off the update.

Just a note to anyone switching version, imports need to be changed from ```angularx-social-login``` to ```@abacritt/angularx-social-login```

**Comment by Heatmanofurioso** [comment]
@rat-matheson Closing this.
But quick question. We've mentioned the need to change the namespace several times in issues, documentation, npm and other places.
Any idea on how to make more people aware of this change?
I notice many Issues pop up sometimes due to people not upgrading to the new namespace

**Comment by rat-matheson** [comment]
Beats me.  At some point, people are just going to be upgraded and it will be a non-issue.  Previously, I was unable to upgrade due to being stuck on angular 12.   The documentation along with the error messages for the most part was sufficient for me.  However, note that the examples in the documentation (at least for the new version you just pushed) import from the old package which might throw some people off.

https://www.npmjs.com/package/@abacritt/angularx-social-login/v/1.2.4-ngx12.0

```
import { SocialLoginModule, SocialAuthServiceConfig } from '@abacritt/angularx-social-login';
import {
  GoogleLoginProvider,
  FacebookLoginProvider
} from 'angularx-social-login';

@NgModule({
...
```

when it probably should be

```
import { SocialLoginModule, SocialAuthServiceConfig } from 'angularx-social-login';
import {
  GoogleLoginProvider,
  FacebookLoginProvider
} from 'angularx-social-login';

@NgModule({
...
```

**Comment by Heatmanofurioso** [comment]
@rat-matheson Thanks for that notice.
I tried to do some quick updates today as soon as possible to try and help the people using it.
I'll update those docs tomorrow, and either release a version to NPM to have it updated in there, or just let that change be released in the next change-pr. Thanks
